version: '3.8'

services:
  nginx:
    container_name: nginx-container
    image: nginx:latest
    depends_on:
      - albalog
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src/config/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  albalog:
    container_name: albalog-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always

  mysql:
    container_name: mysql-container
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - /home/ubuntu/mysql_data:/var/lib/mysql
    env_file:
      - .mysql_env
    restart: always
